In [90]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.linear_model import LinearRegression

In [91]:
import os
os.getcwd()

'c:\\kaggle'

In [92]:
from pathlib import Path

PROJECT_ROOT = Path.cwd() 
# load the datasets
# team_stats = pd.read_csv(PROJECT_ROOT / 'NBA' / 'Stats' / 'TeamStatistics.csv')
team_stats_ext = pd.read_csv(PROJECT_ROOT / 'NBA' / 'Stats' / 'TeamStatisticsExtended.csv')

In [93]:
pd.set_option('display.max_columns', None)

In [94]:
sorted(team_stats_ext.columns.tolist())

['assistPercentage',
 'assistRatio',
 'assistToTurnoverRatio',
 'assists',
 'benchPoints',
 'biggestLead',
 'biggestScoringRun',
 'blocks',
 'blocksAgainst',
 'defensiveRating',
 'defensiveReboundPercentage',
 'effectiveFieldGoalPercentage',
 'estimatedDefensiveRating',
 'estimatedNetRating',
 'estimatedOffensiveRating',
 'estimatedPace',
 'fieldGoalsAttempted',
 'fieldGoalsMade',
 'fieldGoalsPercentage',
 'foulsPersonal',
 'freeThrowAttemptRate',
 'freeThrowsAttempted',
 'freeThrowsMade',
 'freeThrowsPercentage',
 'gameDateTimeEst',
 'gameId',
 'gameLabel',
 'gameSubLabel',
 'gameType',
 'home',
 'leadChanges',
 'netRating',
 'numMinutes',
 'offensiveRating',
 'offensiveReboundPercentage',
 'opponentEffectiveFieldGoalPercentage',
 'opponentFreeThrowAttemptRate',
 'opponentOffensiveReboundPercentage',
 'opponentPointsFastBreak',
 'opponentPointsInPaint',
 'opponentPointsOffTurnovers',
 'opponentPointsSecondChance',
 'opponentScore',
 'opponentTeamCity',
 'opponentTeamId',
 'opponentTeamName',
 'opponentTurnoverPercentage',
 'ot1Points',
 'ot2Points',
 'otAllPoints',
 'pace',
 'pacePer40',
 'percentAssisted2PointMade',
 'percentAssisted3PointMade',
 'percentAssistedFieldGoalsMade',
 'percentFieldGoalAttempts2Point',
 'percentFieldGoalAttempts3Point',
 'percentPoints2Point',
 'percentPoints2PointMidRange',
 'percentPoints3Point',
 'percentPointsFastBreak',
 'percentPointsFreeThrow',
 'percentPointsInPaint',
 'percentPointsOffTurnovers',
 'percentUnassisted2PointMade',
 'percentUnassisted3PointMade',
 'percentUnassistedFieldGoalsMade',
 'personalFoulsDrawn',
 'playerImpactEstimate',
 'plusMinusPoints',
 'pointsFastBreak',
 'pointsFromTurnovers',
 'pointsInThePaint',
 'pointsOffTurnovers',
 'pointsSecondChance',
 'possessions',
 'q1Points',
 'q2Points',
 'q3Points',
 'q4Points',
 'reboundPercentage',
 'reboundsDefensive',
 'reboundsOffensive',
 'reboundsTeam',
 'reboundsTotal',
 'seasonLosses',
 'seasonWins',
 'seed',
 'seriesGameNumber',
 'steals',
 'teamCity',
 'teamId',
 'teamName',
 'teamScore',
 'teamTurnoverPercentage',
 'threePointersAttempted',
 'threePointersMade',
 'threePointersPercentage',
 'timeoutsRemaining',
 'timesTied',
 'trueShootingPercentage',
 'turnovers',
 'turnoversTeam',
 'win']

In [95]:
team_stats_ext

,gameId,gameDateTimeEst,gameType,gameLabel,gameSubLabel,seriesGameNumber,teamId,teamCity,teamName,opponentTeamId,opponentTeamCity,opponentTeamName,home,win,teamScore,opponentScore,seed,numMinutes,assists,steals,blocks,blocksAgainst,fieldGoalsMade,fieldGoalsAttempted,fieldGoalsPercentage,threePointersMade,threePointersAttempted,threePointersPercentage,freeThrowsMade,freeThrowsAttempted,freeThrowsPercentage,reboundsOffensive,reboundsDefensive,reboundsTotal,reboundsTeam,foulsPersonal,personalFoulsDrawn,turnovers,turnoversTeam,plusMinusPoints,q1Points,q2Points,q3Points,q4Points,ot1Points,ot2Points,otAllPoints,benchPoints,biggestLead,biggestScoringRun,leadChanges,pointsFastBreak,pointsFromTurnovers,pointsInThePaint,pointsSecondChance,timesTied,timeoutsRemaining,seasonWins,seasonLosses,estimatedOffensiveRating,offensiveRating,estimatedDefensiveRating,defensiveRating,estimatedNetRating,netRating,assistPercentage,assistToTurnoverRatio,assistRatio,offensiveReboundPercentage,defensiveReboundPercentage,reboundPercentage,teamTurnoverPercentage,effectiveFieldGoalPercentage,trueShootingPercentage,estimatedPace,pace,pacePer40,possessions,playerImpactEstimate,pointsOffTurnovers,opponentPointsOffTurnovers,opponentPointsSecondChance,opponentPointsFastBreak,opponentPointsInPaint,percentFieldGoalAttempts2Point,percentFieldGoalAttempts3Point,percentPoints2Point,percentPoints2PointMidRange,percentPoints3Point,percentPointsFastBreak,percentPointsFreeThrow,percentPointsOffTurnovers,percentPointsInPaint,percentAssisted2PointMade,percentUnassisted2PointMade,percentAssisted3PointMade,percentUnassisted3PointMade,percentAssistedFieldGoalsMade,percentUnassistedFieldGoalsMade,freeThrowAttemptRate,opponentEffectiveFieldGoalPercentage,opponentFreeThrowAttemptRate,opponentTurnoverPercentage,opponentOffensiveReboundPercentage
0,42500405,2026-06-13 20:30:00,Playoffs,NBA Finals,Game 5,5.0,1610612759,San Antonio,Spurs,1610612752,New York,Knicks,1,0,90,94,2.0,240.0,18,6,7,4,33,86,0.384,12,37,0.324,12,19,0.632,14,33,47,12.0,22,21,12,1.0,-4.0,23.0,19.0,30.0,18.0,NaN,NaN,NaN,32.0,16.0,9.0,5.0,13.0,21.0,38.0,17.0,5.0,0.0,1.0,4.0,96.4,100.0,93.7,103.3,2.7,-3.3,0.545,1.38,14.2,0.339,0.593,0.470,0.144,0.453,0.477,96.8,90.5,75.42,90,0.508,21.0,18.0,14.0,13.0,30.0,0.570,0.430,0.467,0.044,0.400,0.144,0.133,0.233,0.422,0.381,0.619,0.833,0.167,0.545,0.455,0.221,0.425,0.322,0.154,0.407
1,42500405,2026-06-13 20:30:00,Playoffs,NBA Finals,Game 5,5.0,1610612752,New York,Knicks,1610612759,San Antonio,Spurs,0,1,94,90,3.0,240.0,14,8,4,7,31,87,0.356,12,37,0.324,20,28,0.714,13,35,48,18.0,21,22,10,4.0,4.0,13.0,24.0,28.0,29.0,NaN,NaN,NaN,9.0,4.0,10.0,5.0,13.0,18.0,30.0,14.0,5.0,0.0,4.0,1.0,93.7,103.3,96.4,100.0,-2.7,3.3,0.452,1.00,10.9,0.407,0.661,0.530,0.154,0.425,0.473,96.8,90.5,75.42,91,0.492,18.0,21.0,17.0,13.0,38.0,0.575,0.425,0.404,0.085,0.383,0.138,0.213,0.191,0.319,0.263,0.737,0.750,0.250,0.452,0.548,0.322,0.453,0.221,0.144,0.339
2,42500404,2026-06-10 20:30:00,Playoffs,NBA Finals,Game 4,4.0,1610612759,San Antonio,Spurs,1610612752,New York,Knicks,0,0,106,107,2.0,240.0,24,10,4,4,36,86,0.419,17,43,0.395,17,20,0.850,12,30,42,8.0,21,21,11,1.0,-1.0,41.0,35.0,14.0,16.0,NaN,NaN,NaN,28.0,29.0,10.0,3.0,12.0,25.0,28.0,10.0,2.0,0.0,1.0,3.0,111.8,112.8,109.9,115.1,1.9,-2.3,0.667,2.00,17.9,0.308,0.717,0.500,0.128,0.517,0.559,96.1,93.5,77.92,94,0.514,25.0,11.0,14.0,13.0,34.0,0.500,0.500,0.358,0.094,0.481,0.113,0.160,0.236,0.264,0.421,0.579,0.941,0.059,0.667,0.333,0.233,0.558,0.359,0.161,0.283
3,42500404,2026-06-10 20:30:00,Playoffs,NBA Finals,Game 4,4.0,1610612752,New York,Knicks,1610612759,San Antonio,Spurs,1,1,107,106,3.0,240.0,23,6,4,4,36,78,0.462,15,32,0.469,20,28,0.714,8,31,39,14.0,21,21,13,2.0,1.0,22.0,27.0,26.0,32.0,NaN,NaN,NaN,12.0,1.0,13.0,3.0,13.0,11.0,34.0,14.0,2.0,0.0,3.0,1.0,109.9,115.1,111.8,112.8,-1.9,2.3,0.639,1.53,17.8,0.283,0.692,0.500,0.161,0.558,0.592,96.1,93.5,77.92,93,0.486,11.0,25.0,10.0,12.0,28.0,0.590,0.410,0.393,0.075,0.421,0.121,0.187,0.103,0.318,0.381,0.619,1.000,0.000,0.639,0.361,0.359,0.517,0.233,0.128,0.308
4,42500403,2026-06-08 20:30:00,Playoffs,NBA Finals,Game 3,3.0,1610612759,San Antonio,Spurs,1610612752,New York,Knicks,0,1,115,111,2.0,240.0,28,7,7,6,39,84,0.464,12,34,0.353,25,32,0.781,6,31,37,11.0,21,23,8,0.0,4.0,33.0,24.0,35.0,23.0,NaN,NaN,NaN,25.0,12.0,7.0,6.0,5.0,21.0,44.0,10.0,4.0,0.0,1.0,2.0,114.9,123.7,112.5,119.4,2.4,4.3,0.718,3.50,20.9,0.265,0.627,0.450,0.086,0.536,0.586,99.4,93.0,77.50,93,0.548,21.0,7.0,21.0,15.0,46.0,0.595,0.405,0.470,0.087,0.313,0.043,0.217,0.183,0.383,0.630,0.370,0.917,0.083,0.718,0.282,0.381,0.528,0.250,0.140,0.373
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
79719,29600005,1996-11-01 19:30:00,Regular Season,NaN,NaN,NaN,1610612737,Atlanta,Hawks,1610612748,Miami,Heat,0,0,81,94,NaN,240.0,13,10,7,4,25,65,0.385,4,16,0.250,27,32,0.844,10,30,40,7.0,20,0,24,1.0,-13.0,15.0,24.0,27.0,15.0,NaN,NaN,NaN,81.0,0.0,7.0,0.0,6.0,0.0,32.0,9.0,0.0,0.0,56.0,26.0,87.0,88.0,101.8,102.2,-14.8,-14.1,0.520,0.54,11.1,0.326,0.674,0.506,0.261,0.415,0.512,92.7,92.0,76.67,92,0.428,13.0,17.0,15.0,14.0,32.0,0.754,0.246,0.519,0.123,0.148,0.074,0.333,0.160,0.395,0.429,0.571,1.000,0.000,0.520,0.480,0.492,0.513,0.244,0.207,0.326
79720,29600007,1996-11-01 19:30:00,Regular Season,NaN,NaN,NaN,1610612765,Detroit,Pistons,1610612754,Indiana,Pacers,1,1,95,89,NaN,240.0,12,10,3,4,32,68,0.471,6,20,0.300,25,35,0.714,11,28,39,10.0,22,0,19,2.0,6.0,16.0,25.0,27.0,27.0,NaN,NaN,NaN,95.0,9.0,11.0,7.0,7.0,0.0,30.0,14.0,4.0,0.0,54.0,28.0,103.9,104.4,96.6,96.7,7.3,7.7,0.375,0.63,10.3,0.333,0.689,0.517,0.209,0.515,0.570,91.8,91.5,76.25,91,0.556,15.0,21.0,11.0,4.0,34.0,0.706,0.294,0.547,0.232,0.189,0.074,0.263,0.158,0.316,0.231,0.769,1.000,0.000,0.375,0.625,0.515,0.486,0.311,0.196,0.311
79721,29600007,1996-11-01 19:30:00,Regular Season,NaN,NaN,NaN,1610612754,Indiana,Pacers,1610612765,Detroit,Pistons,0,0,89,95,NaN,240.0,19,6,4,3,33,74,0.446,6,21,0.286,17,23,0.739,10,26,36,8.0,30,0,18,0.0,-6.0,17.0,28.0,14.0,30.0,NaN,NaN,NaN,89.0,10.0,8.0,7.0,4.0,0.0,34.0,11.0,4.0,0.0,39.0,43.0,96.6,96.7,103.9,104.4,-7.3,-7.7,0.576,1.06,15.4,0.311,0.667,0.483,0.196,0.486,0.529,91.8,91.5,76.25,92,0.444,21.0,15.0,14.0,7.0,30.0,0.716,0.284,0.607,0.225,0.202,0.045,0.191,0.236,0.382,0.519,0.481,0.833,0.167,0.576,0.424,0.311,0.515,0.515,0.209,0.333
79722,29600001,1996-11-01 19:00:00,Regular Season,NaN,NaN,NaN,1610612738,Boston,Celtics,1610612741,Chicago,Bulls,1,0,98,107,NaN,240.0,20,10,2,8,38,84,0.452,8,20,0.400,14,23,0.609,14,22,36,11.0,33,0,18,0.0,-9.0,28.0,31.0,18.0,21.0,NaN,NaN,NaN,98.0,16.0,16.0,8.0,15.0,0.0,48.0,16.0,5.0,0.0,15.0,67.0,99.9,103.2,108.0,111.5,-8.1,-8.3,0.526,1.11,15.4,0.327,0.694,0.482,0.189,0.500,0.521,98.6,95.5,79.58,95,0.354,16.0,21.0,12.0,15.0,56.0,0.762,0.238,0.612,0.122,0.245,0.153,0.143,0.163,0.490,0.467,0.533,0.750,0.250,0.526,0.474,0.274,0.574,0.432,0.198,0.306
79723,29600001,1996-11-01 19:00:00,Regular Season,NaN,NaN,NaN,1610612741,Chicago,Bulls,1610612738,Boston,Celtics,0,1,107,98,NaN,240.0,28,7,8,2,42,74,0.568,1,13,0.077,22,32,0.688,8,29,37,13.0,23,0,19,0.0,9.0,27.0,21.0,32.0,27.0,NaN,NaN,NaN,107.0,11.0,13.0,8.0,15.0,0.0,56.0,12.0,5.0,0.0,69.0,13.0,108.0,111.5,99.9,103.2,8.1,8.3,0.667,1.47,21.1,0.306,0.673,0.518,0.198,0.574,0.607,98.6,95.5,79.58,96,0.646,21.0,16.0,16.0,15.0,48.0,0.824,0.176,0.766,0.243,0.028,0.140,0.206,0.196,0.523,0.683,0.317,0.000,1.000,0.667,0.333,0.432,0.500,0.274,0.189,0.327

In [97]:
discrepancy = (
    team_stats_ext['teamScore'] 
    - team_stats_ext['opponentScore'] 
    - team_stats_ext['plusMinusPoints']
)

team_stats_ext[discrepancy.abs() > 0.1].shape

(64, 104)

In [98]:
df = team_stats_ext[discrepancy.abs() > 0.1][['gameId', 'gameDateTimeEst', 'teamName',
       'opponentTeamName', 'teamScore','opponentScore', 'plusMinusPoints']]
df

,gameId,gameDateTimeEst,teamName,opponentTeamName,teamScore,opponentScore,plusMinusPoints
3176,22400988,2025-04-01 20:00:00,Magic,Spurs,0,0,11.0
3177,22400988,2025-04-01 20:00:00,Spurs,Magic,0,0,-11.0
3372,22400627,2025-03-19 21:00:00,Jazz,Wizards,0,0,16.0
3373,22400627,2025-03-19 21:00:00,Wizards,Jazz,0,0,-16.0
22720,21700732,2018-01-28 15:30:00,Suns,Rockets,103,113,-11.0
...,...,...,...,...,...,...,...
78989,29600370,1996-12-22 20:00:00,Mavericks,SuperSonics,76,91,-14.0
79060,29600332,1996-12-17 22:00:00,Warriors,SuperSonics,81,123,-40.0
79061,29600332,1996-12-17 22:00:00,SuperSonics,Warriors,123,81,40.0
79462,29600130,1996-11-19 20:00:00,Magic,Knicks,88,90,-4.0
79463,29600130,1996-11-19 20:00:00,Knicks,Magic,90,88,4.0

In [ ]:
df.iloc[:10]

,gameId,gameDateTimeEst,teamName,opponentTeamName,teamScore,opponentScore,plusMinusPoints
3176,22400988,2025-04-01 20:00:00,Magic,Spurs,0,0,11.0
3177,22400988,2025-04-01 20:00:00,Spurs,Magic,0,0,-11.0
3372,22400627,2025-03-19 21:00:00,Jazz,Wizards,0,0,16.0
3373,22400627,2025-03-19 21:00:00,Wizards,Jazz,0,0,-16.0
22720,21700732,2018-01-28 15:30:00,Suns,Rockets,103,113,-11.0
22721,21700732,2018-01-28 15:30:00,Rockets,Suns,113,103,11.0
39290,21100676,2012-03-20 19:00:00,Clippers,Pacers,89,104,-13.0
39291,21100676,2012-03-20 19:00:00,Pacers,Clippers,104,89,13.0
43268,21000028,2010-10-29 20:30:00,Mavericks,Grizzlies,90,90,-1.0
43269,21000028,2010-10-29 20:30:00,Grizzlies,Mavericks,90,90,1.0

In [ ]:
df['gameId']

3176     22400988
3177     22400988
3372     22400627
3373     22400627
22720    21700732
           ...
78989    29600370
79060    29600332
79061    29600332
79462    29600130
79463    29600130
Name: gameId, Length: 64, dtype: int64

In [ ]:
game_ids = df['gameId'].astype(str).str.zfill(10).unique().tolist()
game_ids

['0022400988',
 '0022400627',
 '0021700732',
 '0021100676',
 '0021000028',
 '0020900539',
 '0010800035',
 '0010700072',
 '0020400346',
 '0020400214',
 '0020400203',
 '0020400143',
 '0020400118',
 '0020400090',
 '0020400081',
 '0020400075',
 '0020400066',
 '0020400060',
 '0020400040',
 '0020400022',
 '0010400119',
 '0010400105',
 '0010400073',
 '0010400069',
 '0040300312',
 '0040300217',
 '0020300778',
 '0010300012',
 '0020200053',
 '0029600370',
 '0029600332',
 '0029600130']

In [ ]:
from nba_api.stats.endpoints import boxscoresummaryv2
import time

results = {}
for gid in game_ids:
    box = boxscoresummaryv2.BoxScoreSummaryV2(game_id=gid)
    line_score = box.line_score.get_data_frame()
    results[gid] = line_score[['TEAM_ABBREVIATION', 'TEAM_CITY_NAME', 'PTS']]
    print(gid)
    print(results[gid])
    print()
    time.sleep(2)

C:\Users\zhang\AppData\Local\Temp\ipykernel_4236\2618714294.py:6: UserWarning: BoxScoreSummaryV2 has known data availability issues. Data may be missing for games on or after 4/10/2025. Users should moving to BoxScoreSummaryV3 or verify data completeness for their specific use cases and implement appropriate error handling.
  box = boxscoresummaryv2.BoxScoreSummaryV2(game_id=gid)

0022400988
  TEAM_ABBREVIATION TEAM_CITY_NAME  PTS
0               ORL        Orlando  116
1               SAS    San Antonio  105

C:\Users\zhang\AppData\Local\Temp\ipykernel_4236\2618714294.py:6: UserWarning: BoxScoreSummaryV2 has known data availability issues. Data may be missing for games on or after 4/10/2025. Users should moving to BoxScoreSummaryV3 or verify data completeness for their specific use cases and implement appropriate error handling.
  box = boxscoresummaryv2.BoxScoreSummaryV2(game_id=gid)

0022400627
  TEAM_ABBREVIATION TEAM_CITY_NAME  PTS
0               UTA           Utah  128
1               WAS     Washington  112

C:\Users\zhang\AppData\Local\Temp\ipykernel_4236\2618714294.py:6: UserWarning: BoxScoreSummaryV2 has known data availability issues. Data may be missing for games on or after 4/10/2025. Users should moving to BoxScoreSummaryV3 or verify data completeness for their specific use cases and implement appropriate error handling.
  box = boxscoresummaryv2.BoxScoreSummaryV2(game_id=gid)

0021700732
  TEAM_ABBREVIATION TEAM_CITY_NAME  PTS
0               HOU        Houston  113
1               PHX        Phoenix  102

C:\Users\zhang\AppData\Local\Temp\ipykernel_4236\2618714294.py:6: UserWarning: BoxScoreSummaryV2 has known data availability issues. Data may be missing for games on or after 4/10/2025. Users should moving to BoxScoreSummaryV3 or verify data completeness for their specific use cases and implement appropriate error handling.
  box = boxscoresummaryv2.BoxScoreSummaryV2(game_id=gid)

0021100676
  TEAM_ABBREVIATION TEAM_CITY_NAME  PTS
0               LAC    Los Angeles   89
1               IND        Indiana  102

C:\Users\zhang\AppData\Local\Temp\ipykernel_4236\2618714294.py:6: UserWarning: BoxScoreSummaryV2 has known data availability issues. Data may be missing for games on or after 4/10/2025. Users should moving to BoxScoreSummaryV3 or verify data completeness for their specific use cases and implement appropriate error handling.
  box = boxscoresummaryv2.BoxScoreSummaryV2(game_id=gid)

0021000028
  TEAM_ABBREVIATION TEAM_CITY_NAME  PTS
0               DAL         Dallas   90
1               MEM        Memphis   91

C:\Users\zhang\AppData\Local\Temp\ipykernel_4236\2618714294.py:6: UserWarning: BoxScoreSummaryV2 has known data availability issues. Data may be missing for games on or after 4/10/2025. Users should moving to BoxScoreSummaryV3 or verify data completeness for their specific use cases and implement appropriate error handling.
  box = boxscoresummaryv2.BoxScoreSummaryV2(game_id=gid)

0020900539
  TEAM_ABBREVIATION TEAM_CITY_NAME  PTS
0               NOH    New Orleans  115
1               WAS     Washington  110

C:\Users\zhang\AppData\Local\Temp\ipykernel_4236\2618714294.py:6: UserWarning: BoxScoreSummaryV2 has known data availability issues. Data may be missing for games on or after 4/10/2025. Users should moving to BoxScoreSummaryV3 or verify data completeness for their specific use cases and implement appropriate error handling.
  box = boxscoresummaryv2.BoxScoreSummaryV2(game_id=gid)

0010800035
  TEAM_ABBREVIATION TEAM_CITY_NAME  PTS
0               DEN         Denver   77
1               PHX        Phoenix   72

C:\Users\zhang\AppData\Local\Temp\ipykernel_4236\2618714294.py:6: UserWarning: BoxScoreSummaryV2 has known data availability issues. Data may be missing for games on or after 4/10/2025. Users should moving to BoxScoreSummaryV3 or verify data completeness for their specific use cases and implement appropriate error handling.
  box = boxscoresummaryv2.BoxScoreSummaryV2(game_id=gid)

0010700072
  TEAM_ABBREVIATION TEAM_CITY_NAME  PTS
0               BOS         Boston   36
1               NJN     New Jersey   33

C:\Users\zhang\AppData\Local\Temp\ipykernel_4236\2618714294.py:6: UserWarning: BoxScoreSummaryV2 has known data availability issues. Data may be missing for games on or after 4/10/2025. Users should moving to BoxScoreSummaryV3 or verify data completeness for their specific use cases and implement appropriate error handling.
  box = boxscoresummaryv2.BoxScoreSummaryV2(game_id=gid)

0020400346
  TEAM_ABBREVIATION TEAM_CITY_NAME  PTS
0               ATL        Atlanta   68
1               DAL         Dallas   90

C:\Users\zhang\AppData\Local\Temp\ipykernel_4236\2618714294.py:6: UserWarning: BoxScoreSummaryV2 has known data availability issues. Data may be missing for games on or after 4/10/2025. Users should moving to BoxScoreSummaryV3 or verify data completeness for their specific use cases and implement appropriate error handling.
  box = boxscoresummaryv2.BoxScoreSummaryV2(game_id=gid)

0020400214
  TEAM_ABBREVIATION TEAM_CITY_NAME  PTS
0               NYK       New York   90
1               MEM        Memphis   82

C:\Users\zhang\AppData\Local\Temp\ipykernel_4236\2618714294.py:6: UserWarning: BoxScoreSummaryV2 has known data availability issues. Data may be missing for games on or after 4/10/2025. Users should moving to BoxScoreSummaryV3 or verify data completeness for their specific use cases and implement appropriate error handling.
  box = boxscoresummaryv2.BoxScoreSummaryV2(game_id=gid)

0020400203
  TEAM_ABBREVIATION TEAM_CITY_NAME  PTS
0               ATL        Atlanta  109
1               NYK       New York  110

C:\Users\zhang\AppData\Local\Temp\ipykernel_4236\2618714294.py:6: UserWarning: BoxScoreSummaryV2 has known data availability issues. Data may be missing for games on or after 4/10/2025. Users should moving to BoxScoreSummaryV3 or verify data completeness for their specific use cases and implement appropriate error handling.
  box = boxscoresummaryv2.BoxScoreSummaryV2(game_id=gid)

0020400143
  TEAM_ABBREVIATION TEAM_CITY_NAME  PTS
0               DAL         Dallas   82
1               DEN         Denver  110

C:\Users\zhang\AppData\Local\Temp\ipykernel_4236\2618714294.py:6: UserWarning: BoxScoreSummaryV2 has known data availability issues. Data may be missing for games on or after 4/10/2025. Users should moving to BoxScoreSummaryV3 or verify data completeness for their specific use cases and implement appropriate error handling.
  box = boxscoresummaryv2.BoxScoreSummaryV2(game_id=gid)

0020400118
  TEAM_ABBREVIATION TEAM_CITY_NAME  PTS
0               CLE      Cleveland  106
1               CHA      Charlotte   89

C:\Users\zhang\AppData\Local\Temp\ipykernel_4236\2618714294.py:6: UserWarning: BoxScoreSummaryV2 has known data availability issues. Data may be missing for games on or after 4/10/2025. Users should moving to BoxScoreSummaryV3 or verify data completeness for their specific use cases and implement appropriate error handling.
  box = boxscoresummaryv2.BoxScoreSummaryV2(game_id=gid)

0020400090
  TEAM_ABBREVIATION TEAM_CITY_NAME  PTS
0               POR       Portland  105
1               TOR        Toronto  102

C:\Users\zhang\AppData\Local\Temp\ipykernel_4236\2618714294.py:6: UserWarning: BoxScoreSummaryV2 has known data availability issues. Data may be missing for games on or after 4/10/2025. Users should moving to BoxScoreSummaryV3 or verify data completeness for their specific use cases and implement appropriate error handling.
  box = boxscoresummaryv2.BoxScoreSummaryV2(game_id=gid)

0020400081
  TEAM_ABBREVIATION TEAM_CITY_NAME  PTS
0               CLE      Cleveland  105
1               WAS     Washington   74

C:\Users\zhang\AppData\Local\Temp\ipykernel_4236\2618714294.py:6: UserWarning: BoxScoreSummaryV2 has known data availability issues. Data may be missing for games on or after 4/10/2025. Users should moving to BoxScoreSummaryV3 or verify data completeness for their specific use cases and implement appropriate error handling.
  box = boxscoresummaryv2.BoxScoreSummaryV2(game_id=gid)

0020400075
  TEAM_ABBREVIATION TEAM_CITY_NAME  PTS
0               LAC    Los Angeles   96
1               NYK       New York  110

C:\Users\zhang\AppData\Local\Temp\ipykernel_4236\2618714294.py:6: UserWarning: BoxScoreSummaryV2 has known data availability issues. Data may be missing for games on or after 4/10/2025. Users should moving to BoxScoreSummaryV3 or verify data completeness for their specific use cases and implement appropriate error handling.
  box = boxscoresummaryv2.BoxScoreSummaryV2(game_id=gid)

0020400066
  TEAM_ABBREVIATION TEAM_CITY_NAME  PTS
0               GSW   Golden State   71
1               SAS    San Antonio   91

C:\Users\zhang\AppData\Local\Temp\ipykernel_4236\2618714294.py:6: UserWarning: BoxScoreSummaryV2 has known data availability issues. Data may be missing for games on or after 4/10/2025. Users should moving to BoxScoreSummaryV3 or verify data completeness for their specific use cases and implement appropriate error handling.
  box = boxscoresummaryv2.BoxScoreSummaryV2(game_id=gid)

0020400060
  TEAM_ABBREVIATION TEAM_CITY_NAME  PTS
0               NJN     New Jersey  100
1               PHI   Philadelphia  108

C:\Users\zhang\AppData\Local\Temp\ipykernel_4236\2618714294.py:6: UserWarning: BoxScoreSummaryV2 has known data availability issues. Data may be missing for games on or after 4/10/2025. Users should moving to BoxScoreSummaryV3 or verify data completeness for their specific use cases and implement appropriate error handling.
  box = boxscoresummaryv2.BoxScoreSummaryV2(game_id=gid)

0020400040
  TEAM_ABBREVIATION TEAM_CITY_NAME  PTS
0               DEN         Denver   82
1               UTA           Utah  106

C:\Users\zhang\AppData\Local\Temp\ipykernel_4236\2618714294.py:6: UserWarning: BoxScoreSummaryV2 has known data availability issues. Data may be missing for games on or after 4/10/2025. Users should moving to BoxScoreSummaryV3 or verify data completeness for their specific use cases and implement appropriate error handling.
  box = boxscoresummaryv2.BoxScoreSummaryV2(game_id=gid)

0020400022
  TEAM_ABBREVIATION TEAM_CITY_NAME  PTS
0               BOS         Boston   94
1               IND        Indiana  100

C:\Users\zhang\AppData\Local\Temp\ipykernel_4236\2618714294.py:6: UserWarning: BoxScoreSummaryV2 has known data availability issues. Data may be missing for games on or after 4/10/2025. Users should moving to BoxScoreSummaryV3 or verify data completeness for their specific use cases and implement appropriate error handling.
  box = boxscoresummaryv2.BoxScoreSummaryV2(game_id=gid)

0010400119
  TEAM_ABBREVIATION TEAM_CITY_NAME  PTS
0               PHX        Phoenix  122
1               SAC     Sacramento   96

C:\Users\zhang\AppData\Local\Temp\ipykernel_4236\2618714294.py:6: UserWarning: BoxScoreSummaryV2 has known data availability issues. Data may be missing for games on or after 4/10/2025. Users should moving to BoxScoreSummaryV3 or verify data completeness for their specific use cases and implement appropriate error handling.
  box = boxscoresummaryv2.BoxScoreSummaryV2(game_id=gid)

0010400105
  TEAM_ABBREVIATION TEAM_CITY_NAME  PTS
0               GSW   Golden State   83
1               LAC    Los Angeles   76

C:\Users\zhang\AppData\Local\Temp\ipykernel_4236\2618714294.py:6: UserWarning: BoxScoreSummaryV2 has known data availability issues. Data may be missing for games on or after 4/10/2025. Users should moving to BoxScoreSummaryV3 or verify data completeness for their specific use cases and implement appropriate error handling.
  box = boxscoresummaryv2.BoxScoreSummaryV2(game_id=gid)

0010400073
  TEAM_ABBREVIATION TEAM_CITY_NAME  PTS
0               ATL        Atlanta   72
1               MEM        Memphis  100

C:\Users\zhang\AppData\Local\Temp\ipykernel_4236\2618714294.py:6: UserWarning: BoxScoreSummaryV2 has known data availability issues. Data may be missing for games on or after 4/10/2025. Users should moving to BoxScoreSummaryV3 or verify data completeness for their specific use cases and implement appropriate error handling.
  box = boxscoresummaryv2.BoxScoreSummaryV2(game_id=gid)

0010400069
  TEAM_ABBREVIATION TEAM_CITY_NAME  PTS
0               LAC    Los Angeles   94
1               LAL    Los Angeles  113

C:\Users\zhang\AppData\Local\Temp\ipykernel_4236\2618714294.py:6: UserWarning: BoxScoreSummaryV2 has known data availability issues. Data may be missing for games on or after 4/10/2025. Users should moving to BoxScoreSummaryV3 or verify data completeness for their specific use cases and implement appropriate error handling.
  box = boxscoresummaryv2.BoxScoreSummaryV2(game_id=gid)

0040300312
  TEAM_ABBREVIATION TEAM_CITY_NAME  PTS
0               LAL    Los Angeles   71
1               MIN      Minnesota   89

C:\Users\zhang\AppData\Local\Temp\ipykernel_4236\2618714294.py:6: UserWarning: BoxScoreSummaryV2 has known data availability issues. Data may be missing for games on or after 4/10/2025. Users should moving to BoxScoreSummaryV3 or verify data completeness for their specific use cases and implement appropriate error handling.
  box = boxscoresummaryv2.BoxScoreSummaryV2(game_id=gid)

0040300217
  TEAM_ABBREVIATION TEAM_CITY_NAME  PTS
0               NJN     New Jersey   69
1               DET        Detroit   90

C:\Users\zhang\AppData\Local\Temp\ipykernel_4236\2618714294.py:6: UserWarning: BoxScoreSummaryV2 has known data availability issues. Data may be missing for games on or after 4/10/2025. Users should moving to BoxScoreSummaryV3 or verify data completeness for their specific use cases and implement appropriate error handling.
  box = boxscoresummaryv2.BoxScoreSummaryV2(game_id=gid)

0020300778
  TEAM_ABBREVIATION TEAM_CITY_NAME  PTS
0               NOH    New Orleans  120
1               WAS     Washington   98

C:\Users\zhang\AppData\Local\Temp\ipykernel_4236\2618714294.py:6: UserWarning: BoxScoreSummaryV2 has known data availability issues. Data may be missing for games on or after 4/10/2025. Users should moving to BoxScoreSummaryV3 or verify data completeness for their specific use cases and implement appropriate error handling.
  box = boxscoresummaryv2.BoxScoreSummaryV2(game_id=gid)

0010300012
  TEAM_ABBREVIATION TEAM_CITY_NAME  PTS
0               CHI        Chicago   58
1               IND        Indiana   62

C:\Users\zhang\AppData\Local\Temp\ipykernel_4236\2618714294.py:6: UserWarning: BoxScoreSummaryV2 has known data availability issues. Data may be missing for games on or after 4/10/2025. Users should moving to BoxScoreSummaryV3 or verify data completeness for their specific use cases and implement appropriate error handling.
  box = boxscoresummaryv2.BoxScoreSummaryV2(game_id=gid)

0020200053
  TEAM_ABBREVIATION TEAM_CITY_NAME  PTS
0               CLE      Cleveland   89
1               LAL    Los Angeles   70

C:\Users\zhang\AppData\Local\Temp\ipykernel_4236\2618714294.py:6: UserWarning: BoxScoreSummaryV2 has known data availability issues. Data may be missing for games on or after 4/10/2025. Users should moving to BoxScoreSummaryV3 or verify data completeness for their specific use cases and implement appropriate error handling.
  box = boxscoresummaryv2.BoxScoreSummaryV2(game_id=gid)

0029600370
  TEAM_ABBREVIATION TEAM_CITY_NAME  PTS
0               DAL         Dallas   79
1               SEA        Seattle   93

C:\Users\zhang\AppData\Local\Temp\ipykernel_4236\2618714294.py:6: UserWarning: BoxScoreSummaryV2 has known data availability issues. Data may be missing for games on or after 4/10/2025. Users should moving to BoxScoreSummaryV3 or verify data completeness for their specific use cases and implement appropriate error handling.
  box = boxscoresummaryv2.BoxScoreSummaryV2(game_id=gid)

0029600332
  TEAM_ABBREVIATION TEAM_CITY_NAME  PTS
0               GSW   Golden State   83
1               SEA        Seattle  123

C:\Users\zhang\AppData\Local\Temp\ipykernel_4236\2618714294.py:6: UserWarning: BoxScoreSummaryV2 has known data availability issues. Data may be missing for games on or after 4/10/2025. Users should moving to BoxScoreSummaryV3 or verify data completeness for their specific use cases and implement appropriate error handling.
  box = boxscoresummaryv2.BoxScoreSummaryV2(game_id=gid)

0029600130
  TEAM_ABBREVIATION TEAM_CITY_NAME  PTS
0               NYK       New York   92
1               ORL        Orlando   88

In [99]:
results

{'0022400988':   TEAM_ABBREVIATION TEAM_CITY_NAME  PTS
 0               ORL        Orlando  116
 1               SAS    San Antonio  105,
 '0022400627':   TEAM_ABBREVIATION TEAM_CITY_NAME  PTS
 0               UTA           Utah  128
 1               WAS     Washington  112,
 '0021700732':   TEAM_ABBREVIATION TEAM_CITY_NAME  PTS
 0               HOU        Houston  113
 1               PHX        Phoenix  102,
 '0021100676':   TEAM_ABBREVIATION TEAM_CITY_NAME  PTS
 0               LAC    Los Angeles   89
 1               IND        Indiana  102,
 '0021000028':   TEAM_ABBREVIATION TEAM_CITY_NAME  PTS
 0               DAL         Dallas   90
 1               MEM        Memphis   91,
 '0020900539':   TEAM_ABBREVIATION TEAM_CITY_NAME  PTS
 0               NOH    New Orleans  115
 1               WAS     Washington  110,
 '0010800035':   TEAM_ABBREVIATION TEAM_CITY_NAME  PTS
 0               DEN         Denver   77
 1               PHX        Phoenix   72,
 '0010700072':   TEAM_ABBREVIATION TEAM_CITY_NAME  PTS
 0               BOS         Boston   36
 1               NJN     New Jersey   33,
 '0020400346':   TEAM_ABBREVIATION TEAM_CITY_NAME  PTS
 0               ATL        Atlanta   68
 1               DAL         Dallas   90,
 '0020400214':   TEAM_ABBREVIATION TEAM_CITY_NAME  PTS
 0               NYK       New York   90
 1               MEM        Memphis   82,
 '0020400203':   TEAM_ABBREVIATION TEAM_CITY_NAME  PTS
 0               ATL        Atlanta  109
 1               NYK       New York  110,
 '0020400143':   TEAM_ABBREVIATION TEAM_CITY_NAME  PTS
 0               DAL         Dallas   82
 1               DEN         Denver  110,
 '0020400118':   TEAM_ABBREVIATION TEAM_CITY_NAME  PTS
 0               CLE      Cleveland  106
 1               CHA      Charlotte   89,
 '0020400090':   TEAM_ABBREVIATION TEAM_CITY_NAME  PTS
 0               POR       Portland  105
 1               TOR        Toronto  102,
 '0020400081':   TEAM_ABBREVIATION TEAM_CITY_NAME  PTS
 0               CLE      Cleveland  105
 1               WAS     Washington   74,
 '0020400075':   TEAM_ABBREVIATION TEAM_CITY_NAME  PTS
 0               LAC    Los Angeles   96
 1               NYK       New York  110,
 '0020400066':   TEAM_ABBREVIATION TEAM_CITY_NAME  PTS
 0               GSW   Golden State   71
 1               SAS    San Antonio   91,
 '0020400060':   TEAM_ABBREVIATION TEAM_CITY_NAME  PTS
 0               NJN     New Jersey  100
 1               PHI   Philadelphia  108,
 '0020400040':   TEAM_ABBREVIATION TEAM_CITY_NAME  PTS
 0               DEN         Denver   82
 1               UTA           Utah  106,
 '0020400022':   TEAM_ABBREVIATION TEAM_CITY_NAME  PTS
 0               BOS         Boston   94
 1               IND        Indiana  100,
 '0010400119':   TEAM_ABBREVIATION TEAM_CITY_NAME  PTS
 0               PHX        Phoenix  122
 1               SAC     Sacramento   96,
 '0010400105':   TEAM_ABBREVIATION TEAM_CITY_NAME  PTS
 0               GSW   Golden State   83
 1               LAC    Los Angeles   76,
 '0010400073':   TEAM_ABBREVIATION TEAM_CITY_NAME  PTS
 0               ATL        Atlanta   72
 1               MEM        Memphis  100,
 '0010400069':   TEAM_ABBREVIATION TEAM_CITY_NAME  PTS
 0               LAC    Los Angeles   94
 1               LAL    Los Angeles  113,
 '0040300312':   TEAM_ABBREVIATION TEAM_CITY_NAME  PTS
 0               LAL    Los Angeles   71
 1               MIN      Minnesota   89,
 '0040300217':   TEAM_ABBREVIATION TEAM_CITY_NAME  PTS
 0               NJN     New Jersey   69
 1               DET        Detroit   90,
 '0020300778':   TEAM_ABBREVIATION TEAM_CITY_NAME  PTS
 0               NOH    New Orleans  120
 1               WAS     Washington   98,
 '0010300012':   TEAM_ABBREVIATION TEAM_CITY_NAME  PTS
 0               CHI        Chicago   58
 1               IND        Indiana   62,
 '0020200053':   TEAM_ABBREVIATION TEAM_CITY_NAME  PTS
 0               CLE      Cleveland   89
 1               LAL    Los Angeles   70,
 '0029600370':   TEAM_ABBREVIATION TEAM_CITY_NAME  PTS
 0               DAL         Dallas   79
 1               SEA        Seattle   93,
 '0029600332':   TEAM_ABBREVIATION TEAM_CITY_NAME  PTS
 0               GSW   Golden State   83
 1               SEA        Seattle  123,
 '0029600130':   TEAM_ABBREVIATION TEAM_CITY_NAME  PTS
 0               NYK       New York   92
 1               ORL        Orlando   88}

In [100]:
corrections = {}
for gid, line_score in results.items():
    rows = line_score.reset_index(drop=True)
    team0_pts = rows.loc[0, 'PTS']
    team1_pts = rows.loc[1, 'PTS']
    team0_abbr = rows.loc[0, 'TEAM_ABBREVIATION']
    team1_abbr = rows.loc[1, 'TEAM_ABBREVIATION']
    
    corrections[(gid, team0_abbr)] = {'teamScore': team0_pts, 'opponentScore': team1_pts}
    corrections[(gid, team1_abbr)] = {'teamScore': team1_pts, 'opponentScore': team0_pts}

corrections

{('0022400988', 'ORL'): {'teamScore': np.int64(116),
  'opponentScore': np.int64(105)},
 ('0022400988', 'SAS'): {'teamScore': np.int64(105),
  'opponentScore': np.int64(116)},
 ('0022400627', 'UTA'): {'teamScore': np.int64(128),
  'opponentScore': np.int64(112)},
 ('0022400627', 'WAS'): {'teamScore': np.int64(112),
  'opponentScore': np.int64(128)},
 ('0021700732', 'HOU'): {'teamScore': np.int64(113),
  'opponentScore': np.int64(102)},
 ('0021700732', 'PHX'): {'teamScore': np.int64(102),
  'opponentScore': np.int64(113)},
 ('0021100676', 'LAC'): {'teamScore': np.int64(89),
  'opponentScore': np.int64(102)},
 ('0021100676', 'IND'): {'teamScore': np.int64(102),
  'opponentScore': np.int64(89)},
 ('0021000028', 'DAL'): {'teamScore': np.int64(90),
  'opponentScore': np.int64(91)},
 ('0021000028', 'MEM'): {'teamScore': np.int64(91),
  'opponentScore': np.int64(90)},
 ('0020900539', 'NOH'): {'teamScore': np.int64(115),
  'opponentScore': np.int64(110)},
 ('0020900539', 'WAS'): {'teamScore': np.int64(110),
  'opponentScore': np.int64(115)},
 ('0010800035', 'DEN'): {'teamScore': np.int64(77),
  'opponentScore': np.int64(72)},
 ('0010800035', 'PHX'): {'teamScore': np.int64(72),
  'opponentScore': np.int64(77)},
 ('0010700072', 'BOS'): {'teamScore': np.int64(36),
  'opponentScore': np.int64(33)},
 ('0010700072', 'NJN'): {'teamScore': np.int64(33),
  'opponentScore': np.int64(36)},
 ('0020400346', 'ATL'): {'teamScore': np.int64(68),
  'opponentScore': np.int64(90)},
 ('0020400346', 'DAL'): {'teamScore': np.int64(90),
  'opponentScore': np.int64(68)},
 ('0020400214', 'NYK'): {'teamScore': np.int64(90),
  'opponentScore': np.int64(82)},
 ('0020400214', 'MEM'): {'teamScore': np.int64(82),
  'opponentScore': np.int64(90)},
 ('0020400203', 'ATL'): {'teamScore': np.int64(109),
  'opponentScore': np.int64(110)},
 ('0020400203', 'NYK'): {'teamScore': np.int64(110),
  'opponentScore': np.int64(109)},
 ('0020400143', 'DAL'): {'teamScore': np.int64(82),
  'opponentScore': np.int64(110)},
 ('0020400143', 'DEN'): {'teamScore': np.int64(110),
  'opponentScore': np.int64(82)},
 ('0020400118', 'CLE'): {'teamScore': np.int64(106),
  'opponentScore': np.int64(89)},
 ('0020400118', 'CHA'): {'teamScore': np.int64(89),
  'opponentScore': np.int64(106)},
 ('0020400090', 'POR'): {'teamScore': np.int64(105),
  'opponentScore': np.int64(102)},
 ('0020400090', 'TOR'): {'teamScore': np.int64(102),
  'opponentScore': np.int64(105)},
 ('0020400081', 'CLE'): {'teamScore': np.int64(105),
  'opponentScore': np.int64(74)},
 ('0020400081', 'WAS'): {'teamScore': np.int64(74),
  'opponentScore': np.int64(105)},
 ('0020400075', 'LAC'): {'teamScore': np.int64(96),
  'opponentScore': np.int64(110)},
 ('0020400075', 'NYK'): {'teamScore': np.int64(110),
  'opponentScore': np.int64(96)},
 ('0020400066', 'GSW'): {'teamScore': np.int64(71),
  'opponentScore': np.int64(91)},
 ('0020400066', 'SAS'): {'teamScore': np.int64(91),
  'opponentScore': np.int64(71)},
 ('0020400060', 'NJN'): {'teamScore': np.int64(100),
  'opponentScore': np.int64(108)},
 ('0020400060', 'PHI'): {'teamScore': np.int64(108),
  'opponentScore': np.int64(100)},
 ('0020400040', 'DEN'): {'teamScore': np.int64(82),
  'opponentScore': np.int64(106)},
 ('0020400040', 'UTA'): {'teamScore': np.int64(106),
  'opponentScore': np.int64(82)},
 ('0020400022', 'BOS'): {'teamScore': np.int64(94),
  'opponentScore': np.int64(100)},
 ('0020400022', 'IND'): {'teamScore': np.int64(100),
  'opponentScore': np.int64(94)},
 ('0010400119', 'PHX'): {'teamScore': np.int64(122),
  'opponentScore': np.int64(96)},
 ('0010400119', 'SAC'): {'teamScore': np.int64(96),
  'opponentScore': np.int64(122)},
 ('0010400105', 'GSW'): {'teamScore': np.int64(83),
  'opponentScore': np.int64(76)},
 ('0010400105', 'LAC'): {'teamScore': np.int64(76),
  'opponentScore': np.int64(83)},
 ('0010400073', 'ATL'): {'teamScore': np.int64(72),
  'opponentScore': np.int64(100)},
 ('0010400073', 'MEM'): {'teamScore': np.int64(100),
  'opponentScore': np.int64(72)},
 ('0010400069', 'LAC'): {'teamScore': np.int64(94),
  'opponentScore': np.int64(113)},
 ('0010400069', 'LAL'): {'teamScore': np.int64(113),
  'opponentScore': np.int64(94)},
 ('0040300312', 'LAL'): {'teamScore': np.int64(71),
  'opponentScore': np.int64(89)},
 ('0040300312', 'MIN'): {'teamScore': np.int64(89),
  'opponentScore': np.int64(71)},
 ('0040300217', 'NJN'): {'teamScore': np.int64(69),
  'opponentScore': np.int64(90)},
 ('0040300217', 'DET'): {'teamScore': np.int64(90),
  'opponentScore': np.int64(69)},
 ('0020300778', 'NOH'): {'teamScore': np.int64(120),
  'opponentScore': np.int64(98)},
 ('0020300778', 'WAS'): {'teamScore': np.int64(98),
  'opponentScore': np.int64(120)},
 ('0010300012', 'CHI'): {'teamScore': np.int64(58),
  'opponentScore': np.int64(62)},
 ('0010300012', 'IND'): {'teamScore': np.int64(62),
  'opponentScore': np.int64(58)},
 ('0020200053', 'CLE'): {'teamScore': np.int64(89),
  'opponentScore': np.int64(70)},
 ('0020200053', 'LAL'): {'teamScore': np.int64(70),
  'opponentScore': np.int64(89)},
 ('0029600370', 'DAL'): {'teamScore': np.int64(79),
  'opponentScore': np.int64(93)},
 ('0029600370', 'SEA'): {'teamScore': np.int64(93),
  'opponentScore': np.int64(79)},
 ('0029600332', 'GSW'): {'teamScore': np.int64(83),
  'opponentScore': np.int64(123)},
 ('0029600332', 'SEA'): {'teamScore': np.int64(123),
  'opponentScore': np.int64(83)},
 ('0029600130', 'NYK'): {'teamScore': np.int64(92),
  'opponentScore': np.int64(88)},
 ('0029600130', 'ORL'): {'teamScore': np.int64(88),
  'opponentScore': np.int64(92)}}

In [101]:
for (gid, team_abbr), vals in corrections.items():
    mask = (team_stats_ext['gameId'].astype(str).str.zfill(10) == gid)
    team_stats_ext.loc[mask, 'teamScore'] = vals['teamScore']
    team_stats_ext.loc[mask, 'opponentScore'] = vals['opponentScore']
    team_stats_ext.loc[mask, 'plusMinusPoints'] = vals['teamScore'] - vals['opponentScore']

In [102]:
discrepancy2 = (
    team_stats_ext['teamScore'] 
    - team_stats_ext['opponentScore'] 
    - team_stats_ext['plusMinusPoints']
)

team_stats_ext[discrepancy2.abs() > 0.1].shape

(0, 104)

In [103]:
team_stats_ext.to_csv(PROJECT_ROOT / 'NBA' / 'Stats' / 'TeamStatisticsExtended2.csv', index=False)

In [104]:
team_stats_ext.shape

(79724, 104)

In [105]:
# Define a function to map a date to its NBA season "start year"
def get_season_start_year(date):
    if date.month >= 10:  # Oct, Nov, Dec -> season starts this year
        return date.year
    else:  # Jan-June (and any stray summer dates) -> season started previous year
        return date.year - 1

In [106]:
team_stats_ext['gameDateTimeEst'].describe()

count                   79724
unique                  26396
top       2013-04-17 20:00:00
freq                       24
Name: gameDateTimeEst, dtype: object

In [107]:
team_stats_ext['gameDate'] = pd.to_datetime(team_stats_ext['gameDateTimeEst'], errors='coerce').dt.date

In [108]:
team_stats_ext['gameDate'].describe()

count          79724
unique          6476
top       2026-04-12
freq              30
Name: gameDate, dtype: object

In [109]:
team_stats_ext['season'] = team_stats_ext['gameDate'].apply(get_season_start_year).astype('Int64')

In [110]:
team_stats_ext['season']

0        2025
1        2025
2        2025
3        2025
4        2025
         ...
79719    1996
79720    1996
79721    1996
79722    1996
79723    1996
Name: season, Length: 79724, dtype: Int64

In [111]:
start_year = 2010
team_stats_recent = team_stats_ext[team_stats_ext['season'] >= start_year]

In [112]:
team_stats_recent

,gameId,gameDateTimeEst,gameType,gameLabel,gameSubLabel,seriesGameNumber,teamId,teamCity,teamName,opponentTeamId,opponentTeamCity,opponentTeamName,home,win,teamScore,opponentScore,seed,numMinutes,assists,steals,blocks,blocksAgainst,fieldGoalsMade,fieldGoalsAttempted,fieldGoalsPercentage,threePointersMade,threePointersAttempted,threePointersPercentage,freeThrowsMade,freeThrowsAttempted,freeThrowsPercentage,reboundsOffensive,reboundsDefensive,reboundsTotal,reboundsTeam,foulsPersonal,personalFoulsDrawn,turnovers,turnoversTeam,plusMinusPoints,q1Points,q2Points,q3Points,q4Points,ot1Points,ot2Points,otAllPoints,benchPoints,biggestLead,biggestScoringRun,leadChanges,pointsFastBreak,pointsFromTurnovers,pointsInThePaint,pointsSecondChance,timesTied,timeoutsRemaining,seasonWins,seasonLosses,estimatedOffensiveRating,offensiveRating,estimatedDefensiveRating,defensiveRating,estimatedNetRating,netRating,assistPercentage,assistToTurnoverRatio,assistRatio,offensiveReboundPercentage,defensiveReboundPercentage,reboundPercentage,teamTurnoverPercentage,effectiveFieldGoalPercentage,trueShootingPercentage,estimatedPace,pace,pacePer40,possessions,playerImpactEstimate,pointsOffTurnovers,opponentPointsOffTurnovers,opponentPointsSecondChance,opponentPointsFastBreak,opponentPointsInPaint,percentFieldGoalAttempts2Point,percentFieldGoalAttempts3Point,percentPoints2Point,percentPoints2PointMidRange,percentPoints3Point,percentPointsFastBreak,percentPointsFreeThrow,percentPointsOffTurnovers,percentPointsInPaint,percentAssisted2PointMade,percentUnassisted2PointMade,percentAssisted3PointMade,percentUnassisted3PointMade,percentAssistedFieldGoalsMade,percentUnassistedFieldGoalsMade,freeThrowAttemptRate,opponentEffectiveFieldGoalPercentage,opponentFreeThrowAttemptRate,opponentTurnoverPercentage,opponentOffensiveReboundPercentage,gameDate,season
0,42500405,2026-06-13 20:30:00,Playoffs,NBA Finals,Game 5,5.0,1610612759,San Antonio,Spurs,1610612752,New York,Knicks,1,0,90,94,2.0,240.0,18,6,7,4,33,86,0.384,12,37,0.324,12,19,0.632,14,33,47,12.0,22,21,12,1.0,-4.0,23.0,19.0,30.0,18.0,NaN,NaN,NaN,32.0,16.0,9.0,5.0,13.0,21.0,38.0,17.0,5.0,0.0,1.0,4.0,96.4,100.0,93.7,103.3,2.7,-3.3,0.545,1.38,14.2,0.339,0.593,0.470,0.144,0.453,0.477,96.8,90.5,75.42,90,0.508,21.0,18.0,14.0,13.0,30.0,0.570,0.430,0.467,0.044,0.400,0.144,0.133,0.233,0.422,0.381,0.619,0.833,0.167,0.545,0.455,0.221,0.425,0.322,0.154,0.407,2026-06-13,2025
1,42500405,2026-06-13 20:30:00,Playoffs,NBA Finals,Game 5,5.0,1610612752,New York,Knicks,1610612759,San Antonio,Spurs,0,1,94,90,3.0,240.0,14,8,4,7,31,87,0.356,12,37,0.324,20,28,0.714,13,35,48,18.0,21,22,10,4.0,4.0,13.0,24.0,28.0,29.0,NaN,NaN,NaN,9.0,4.0,10.0,5.0,13.0,18.0,30.0,14.0,5.0,0.0,4.0,1.0,93.7,103.3,96.4,100.0,-2.7,3.3,0.452,1.00,10.9,0.407,0.661,0.530,0.154,0.425,0.473,96.8,90.5,75.42,91,0.492,18.0,21.0,17.0,13.0,38.0,0.575,0.425,0.404,0.085,0.383,0.138,0.213,0.191,0.319,0.263,0.737,0.750,0.250,0.452,0.548,0.322,0.453,0.221,0.144,0.339,2026-06-13,2025
2,42500404,2026-06-10 20:30:00,Playoffs,NBA Finals,Game 4,4.0,1610612759,San Antonio,Spurs,1610612752,New York,Knicks,0,0,106,107,2.0,240.0,24,10,4,4,36,86,0.419,17,43,0.395,17,20,0.850,12,30,42,8.0,21,21,11,1.0,-1.0,41.0,35.0,14.0,16.0,NaN,NaN,NaN,28.0,29.0,10.0,3.0,12.0,25.0,28.0,10.0,2.0,0.0,1.0,3.0,111.8,112.8,109.9,115.1,1.9,-2.3,0.667,2.00,17.9,0.308,0.717,0.500,0.128,0.517,0.559,96.1,93.5,77.92,94,0.514,25.0,11.0,14.0,13.0,34.0,0.500,0.500,0.358,0.094,0.481,0.113,0.160,0.236,0.264,0.421,0.579,0.941,0.059,0.667,0.333,0.233,0.558,0.359,0.161,0.283,2026-06-10,2025
3,42500404,2026-06-10 20:30:00,Playoffs,NBA Finals,Game 4,4.0,1610612752,New York,Knicks,1610612759,San Antonio,Spurs,1,1,107,106,3.0,240.0,23,6,4,4,36,78,0.462,15,32,0.469,20,28,0.714,8,31,39,14.0,21,21,13,2.0,1.0,22.0,27.0,26.0,32.0,NaN,NaN,NaN,12.0,1.0,13.0,3.0,13.0,11.0,34.0,14.0,2.0,0.0,3.0,1.0,109.9,115.1,111.8,112.8,-1.9,2.3,0.639,1.53,17.8,0.283,0.692,0.500,0.161,0.558,0.592,96.1,93.5,77.92,93,0.486,11.0,25.0,10.0,12.0,28.0,0.590,0.410,0.393,0.075,0.421,0.121,0.187,0.103,0.318,0.381,0.619,1.000,0.000,0.639,0.361,0.359,0.517,0.233,0.128,0.308,2026-06-10,2025
4,42500403,2026-06-08 20:30:00,Playoffs,NBA Finals,Game 3,3.0,1610612759,San Antonio,Spurs,1610612752,New York,Knicks,0,1,115,111,2.0,240.0,28,7,7,6,39,84,0.464,12,34,0.353,25,32,0.781,6,31,37,11.0,21,23,8,0.0,4.0,33.0,24.0,35.0,23.0,NaN,NaN,NaN,25.0,12.0,7.0,6.0,5.0,21.0,44.0,10.0,4.0,0.0,1.0,2.0,114.9,123.7,112.5,119.4,2.4,4.3,0.718,3.50,20.9,0.265,0.627,0.450,0.086,0.536,0.586,99.4,93.0,77.50,93,0.548,21.0,7.0,21.0,15.0,46.0,0.595,0.405,0.470,0.087,0.313,0.043,0.217,0.183,0.383,0.630,0.370,0.917,0.083,0.718,0.282,0.381,0.528,0.250,0.140,0.373,2026-06-08,2025
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
43541,11000004,2010-10-05 19:00:00,NaN,NaN,NaN,NaN,1610612739,Cleveland,Cavaliers,1610612766,Charlotte,Bobcats,1,1,87,72,NaN,240.0,15,11,8,7,28,77,0.364,3,12,0.250,28,35,0.800,16,43,59,NaN,20,27,20,NaN,15.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,90.2,88.8,71.5,73.5,18.8,15.3,0.536,0.75,11.5,0.309,0.738,0.534,0.204,0.383,0.471,98.6,98.0,81.67,98,0.704,21.0,22.0,12.0,18.0,34.0,0.844,0.156,0.575,0.207,0.103,0.230,0.322,0.241,0.368,0.480,0.520,1.000,0.000,0.536,0.464,0.455,0.329,0.354,0.173,0.262,2010-10-05,2010
43542,11000007,2010-10-05 19:00:00,NaN,NaN,NaN,NaN,1610612751,New Jersey,Nets,1610612755,Philadelphia,76ers,0,1,103,96,NaN,240.0,24,6,3,2,36,71,0.507,8,12,0.667,23,35,0.657,9,39,48,NaN,32,24,18,NaN,7.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,108.0,108.4,101.5,100.0,6.4,8.4,0.667,1.33,18.8,NaN,NaN,NaN,0.189,0.563,0.596,95.0,95.5,79.58,95,0.545,12.0,23.0,4.0,22.0,34.0,0.831,0.169,0.544,0.175,0.233,0.049,0.223,0.117,0.369,0.607,0.393,0.875,0.125,0.667,0.333,0.493,0.389,0.681,0.094,NaN,2010-10-05,2010
43543,11000007,2010-10-05 19:00:00,NaN,NaN,NaN,NaN,1610612755,Philadelphia,76ers,1610612751,New Jersey,Nets,1,0,96,103,NaN,240.0,14,7,2,3,27,72,0.375,2,18,0.111,40,49,0.816,8,31,39,NaN,24,34,9,NaN,-7.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,101.5,100.0,108.0,108.4,-6.4,-8.4,0.519,1.56,11.7,NaN,NaN,NaN,0.094,0.389,0.513,95.0,95.5,79.58,96,0.455,23.0,12.0,2.0,5.0,38.0,0.750,0.250,0.521,0.167,0.063,0.229,0.417,0.240,0.354,0.560,0.440,0.000,1.000,0.519,0.481,0.681,0.563,0.493,0.189,NaN,2010-10-05,2010
43544,11000003,2010-10-04 15:00:00,NaN,NaN,NaN,NaN,1610612750,Minnesota,Timberwolves,1610612747,Los Angeles,Lakers,1,1,111,92,NaN,240.0,26,9,5,4,40,74,0.541,8,12,0.667,23,32,0.719,8,29,37,NaN,25,33,21,NaN,19.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,109.8,112.1,93.4,92.9,16.4,19.2,0.650,1.24,19.1,0.333,0.642,0.517,0.212,0.595,0.630,99.8,99.0,82.50,99,0.642,26.0,21.0,16.0,10.0,34.0,0.838,0.162,0.577,0.252,0.216,0.081,0.207,0.234,0.324,0.594,0.406,0.875,0.125,0.650,0.350,0.432,0.468,0.418,0.222,0.358,2010-10-04,2010
43545,11000003,2010-10-04 15:00:00,NaN,NaN,NaN,NaN,1610612747,Los Angeles,Lakers,1610612750,Minnesota,Timberwolves,0,0,92,111,NaN,240.0,26,14,4,5,35,79,0.443,4,14,0.286,18,33,0.545,17,23,40,NaN,33,25,22,NaN,-19.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,93.4,92.9,109.8,112.1,-16.4,-19.2,0.743,1.18,18.1,0.358,0.667,0.483,0.222,0.468,0.492,99.8,99.0,82.50,99,0.358,21.0,26.0,12.0,9.0,36.0,0.823,0.177,0.674,0.304,0.130,0.109,0.196,0.228,0.370,0.710,0.290,1.000,0.000,0.743,0.257,0.418,0.595,0.432,0.212,0.333,2010-10-04,2010

In [113]:
team_stats_recent.to_csv(PROJECT_ROOT / 'NBA' / 'Stats' / 'TeamStatisticsFrom2010.csv', index=False)